import localFont from "next/font/local";
import "./globals.css";

const instrumentSans = localFont({
  src: "./fonts/InstrumentSans-VariableFont2.ttf",
  variable: "--font-instrument-sans", // Use a CSS variable for the font
  weight: "100 900", // Range of supported weights
  style: "normal", // Since this is a non-italic variant
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${instrumentSans.variable}`}>{children}</body>
    </html>
  );
}
